SELECT CART_ID,NAME FROM CART_PRODUCTS

SELECT NAME,COUNT(NAME) FROM CART_PRODUCTS GROUP BY NAME


SELECT F.NAME as NAME_X, S.NAME as NAME_Y , COUNT(*) as "장바구니 수" FROM CART_PRODUCTS F INNER JOIN CART_PRODUCTS S
ON F.CART_ID = S.CART_ID 
WHERE F.NAME != S.NAME
GROUP BY F.NAME , S.NAME
ORDER BY F.NAME, S.NAME;

SELECT NAME_X , NAME_Y, COUNT(DISTINCT *) as "장바구니 수" from 
(SELECT DISTINCT F.NAME as NAME_X, S.NAME as NAME_Y ,F.CART_ID as "장바구니 수" FROM CART_PRODUCTS F INNER JOIN CART_PRODUCTS S
ON F.CART_ID = S.CART_ID 
WHERE F.NAME != S.NAME
ORDER BY F.NAME, S.NAME;)
GROUP BY NAME_X, NAME_Y